FROM node:21-alpine

RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY package.json tsconfig.json ./

RUN npm install

COPY src ./src
RUN ls -la

RUN npm run build
RUN ls -la

RUN npm prune --omit=dev
RUN ls -la
EXPOSE 3000

# CMD [ "npm", "run", "start" ]
CMD [ "sleep", "infinity" ]
